services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - screenshots:/app/screenshots
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - screenshots:/app/screenshots
    command: celery -A tasks worker --loglevel=info --concurrency=4
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

volumes:
  postgres_data:
  screenshots:
